component_depth: 1
languages:
- go

exclude:
- /examples/myrest/.*
- /examples/store/.*
- /examples/structExample/.*
- /parser/enums/.*
- /parser/interfaces/.*
- /parser/operations/.*
- /parser/structs/.*
- .*/testData/.*

