language: go
go:
 - 1.6.2

install:
 - go get -t ./...
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - PATH="$HOME/gopath/bin:$PATH"
 - go test -v ./...
 - scripts/coverage.sh
 - $HOME/gopath/bin/goveralls -coverprofile=.cover/cover.out -service=travis-ci
