language: go
go:
 - 1.6.2

gobuild_args: -tags ci

install:
 - go get -t ./...
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - PATH="$HOME/gopath/bin:$PATH"
 - go generate
 - go test ./...
 - scripts/coverage.sh
 - $HOME/gopath/bin/goveralls -coverprofile=.cover/cover.out -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash) 